export const capas =  [
  '007 Shitou - The Duel (Japan) - Copia.png',
  '007 Shitou - The Duel (Japan).png',
  '16 Zhang Ma Jiang (China) (Unl) - Copia.png',
  '16 Zhang Ma Jiang (China) (Unl).png',
  '16t (Japan) (SegaNet) - Copia.png',
  '16t (Japan) (SegaNet).png',
  '2020 Toshi Super Baseball (Japan).png',
  '3 Ninjas Kick Back (USA).png',
  '6-Pak (USA).png',
  '688 Attack Sub (USA, Europe) - Copia.png',
  '688 Attack Sub (USA, Europe).png',
  'A Ressha de Ikou MD (Japan).png',
  'Aa Harimanada (Japan).png',
  'AAAHH!!! Real Monsters (USA).png',
  'Action 52 (USA) (Alt) (Unl).png',
  'Action 52 (USA) (Unl).png',
  'Action Replay (Europe) (Program).png',
  'Addams Family Values (Europe) (En,Fr,De).png',
  'Addams Family, The (USA) (Beta) (Alt).png',
  'Addams Family, The (USA) (Beta).png',
  'Addams Family, The (USA, Europe).png',
  'Advanced Busterhawk Gleylancer (Japan).png',
  'Advanced Daisenryaku - Deutsch Dengeki Sakusen (Japan) (Rev A).png',
  'Adventures of Batman & Robin, The (Europe).png',
  'Adventures of Batman & Robin, The (USA).png',
  'Adventures of Mighty Max, The (Europe).png',
  'Adventures of Mighty Max, The (USA).png',
  'Adventures of Rocky and Bullwinkle and Friends, The (USA).png',
  'Aero Blasters (Japan).png',
  'Aero the Acro-Bat (Europe).png',
  'Aero the Acro-Bat (USA).png',
  'Aero the Acro-Bat 2 (Europe).png',
  'Aero the Acro-Bat 2 (USA).png',
  'Aerobiz (USA).png',
  'Aerobiz Supersonic (USA).png',
  'After Burner II (Japan).png',
  'After Burner II (USA, Europe).png',
  'Air Buster (USA).png',
  'Air Diver (Japan).png',
  'Air Diver (USA).png',
  'Air Management - Oozora ni Kakeru (Japan).png',
  'Air Management II - Koukuuou o Mezase (Japan).png',
  'Akumajou Dracula - Vampire Killer (Japan).png',
  'Aladdin (Europe).png',
  'Aladdin (Japan).png',
  'Aladdin (USA) (Beta).png',
  'Aladdin (USA).png',
  'Alex Kidd - Cheongong Maseong (Korea).png',
  'Alex Kidd - Tenkuu Majou (Japan).png',
  'Alex Kidd in the Enchanted Castle (Europe) (Rev A).png',
  'Alex Kidd in the Enchanted Castle (Europe).png',
  'Alex Kidd in the Enchanted Castle (USA).png',
  'Alien 3 (USA, Europe) (Rev A).png',
  'Alien 3 (USA, Europe).png',
  'Alien Soldier (Europe).png',
  'Alien Soldier (Japan).png',
  'Alien Storm (World).png',
  'Alisia Dragoon (Europe).png',
  'Alisia Dragoon (Japan).png',
  'Alisia Dragoon (USA).png',
  'Altered Beast (USA, Europe).png',
  'American Gladiators (USA).png',
  'Andre Agassi Tennis (Europe).png',
  'Andre Agassi Tennis (USA) (Beta).png',
  'Andre Agassi Tennis (USA).png',
  'Animaniacs (Europe) (En,Fr,De).png',
  'Animaniacs (USA).png',
  'Another World (Europe).png',
  'Aoki Ookami to Shiroki Meshika - Genchou Hishi (Japan).png',
  'Aq Renkan Awa (China) (Unl).png',
  'Aquatic Games Starring James Pond and the Aquabats, The (USA, Europe).png',
  'Arcade Classics (USA, Europe).png',
  'Arch Rivals - The Arcade Game (USA, Europe).png',
  'Arcus Odyssey (Japan).png',
  'Arcus Odyssey (USA).png',
  'Ariel the Little Mermaid (USA, Europe).png',
  'Arnold Palmer Tournament Golf (USA, Europe).png',
  'Arrow Flash (Japan).png',
  'Arrow Flash (USA, Europe).png',
  'Art Alive (World).png',
  'Art of Fighting (Europe).png',
  'Art of Fighting (USA).png',
  'Assault Suit Leynos (Japan).png',
  'Asterix and the Great Rescue (Europe) (En,Fr,De,Es,It).png',
  'Asterix and the Great Rescue (USA).png',
  'Asterix and the Power of the Gods (Europe) (Beta).png',
  'Asterix and the Power of the Gods (Europe) (En,Fr,De,Es).png',
  'Atomic Robo-Kid (Japan).png',
  'Atomic Robo-Kid (USA).png',
  'Atomic Runner (Europe).png',
  'Atomic Runner (USA).png',
  'ATP Tour (Europe).png',
  'ATP Tour Championship Tennis (USA).png',
  'Australian Rugby League (Europe).png',
  'Awesome Possum (USA) (Beta).png',
  'Awesome Possum (USA).png',
  'Aworg (Japan) (SegaNet).png',
  'AWS Pro Moves Soccer (USA).png',
  "Ayrton Senna's Super Monaco GP II (Japan, Europe) (En,Ja).png",
  "Ayrton Senna's Super Monaco GP II (USA) (En,Ja).png",
  'B.O.B. (USA) (Beta).png',
  'B.O.B. (USA, Europe).png',
  "Baby's Day Out (USA) (Proto) (Earlier).png",
  "Baby's Day Out (USA) (Proto).png",
  'Back to the Future Part III (Europe).png',
  'Back to the Future Part III (USA).png',
  'Bad Omen (Japan, Korea).png',
  'Bahamut Senki (Japan).png',
  'Ball Jacks (Japan, Europe).png',
  'Ballz 3D - Fighting at Its Ballziest (USA, Europe).png',
  'Barbie Super Model (USA).png',
  'Barbie Vacation Adventure (USA) (Proto).png',
  'Bare Knuckle - Ikari no Tetsuken ~ Streets of Rage (World) (Rev A).png',
  'Bare Knuckle - Ikari no Tetsuken ~ Streets of Rage (World).png',
  'Bare Knuckle II (Japan) (Beta).png',
  'Bare Knuckle II - Shitou heno Chingonka ~ Streets of Rage II (Japan, Europe).png',
  'Bare Knuckle III (Japan).png',
  'Barkley Shut Up and Jam! (USA, Europe).png',
  'Barkley Shut Up and Jam! 2 (USA) (Beta).png',
  'Barkley Shut Up and Jam! 2 (USA).png',
  "Barney's Hide & Seek Game (USA).png",
  'Barver Battle Saga - Tai Kong Zhan Shi (China) (Unl).png',
  'Bass Masters Classic (USA).png',
  'Bass Masters Classic - Pro Edition (USA).png',
  'Batman (Europe).png',
  'Batman (Japan).png',
  'Batman (USA).png',
  'Batman - Revenge of the Joker (USA).png',
  'Batman Forever (World).png',
  'Batman Returns (World).png',
  'Battle Golfer Yui (Japan).png',
  'Battle Mania (Japan).png',
  'Battle Mania Daiginjou (Japan, Korea).png',
  'Battle Squadron (USA, Europe).png',
  'Battlemaster (USA).png',
  'BattleTech - A Game of Armored Combat (USA).png',
  'Battletoads & Double Dragon (USA).png',
  'Battletoads (World).png',
  'Beast Warriors (Japan).png',
  'Beast Wrestler (USA).png',
  "Beauty and the Beast - Belle's Quest (USA).png",
  'Beauty and the Beast - Roar of the Beast (USA).png',
  'Beavis and Butt-Head (Europe).png',
  'Beavis and Butt-Head (USA) (Beta).png',
  'Beavis and Butt-Head (USA).png',
  "Berenstain Bears' Camping Adventure, The (USA).png",
  'Best of the Best - Championship Karate (Europe).png',
  'Best of the Best - Championship Karate (USA).png',
  'Beyond Oasis (USA).png',
  'Beyond Zero Tolerance (USA) (Proto).png',
  'Bible Adventures (USA) (Unl).png',
  'Bill Walsh College Football (USA, Europe).png',
  'Bill Walsh College Football 95 (USA).png',
  'Bimini Run (USA).png',
  'Bio Hazard Battle (USA) (Beta).png',
  'Bio Hazard Battle (USA, Europe).png',
  'Bishoujo Senshi Sailor Moon (Japan).png',
  'Blades of Vengeance (USA, Europe).png',
  'Blaster Master 2 (USA) (Beta).png',
  'Blaster Master 2 (USA).png',
  'Blockbuster World Video Game Championship II (USA).png',
  'Blockout (World).png',
  'Bloodshot (Europe) (En,Fr,De,Es).png',
  'Blue Almanac (Japan).png',
  'Body Count (Europe) (En,Fr,De,Es,It) (Beta).png',
  'Body Count (Europe) (En,Fr,De,Es,It).png',
  'Bonanza Bros. (Japan, Europe) (Rev A).png',
  'Bonanza Bros. (Japan, Europe).png',
  'Bonanza Bros. (USA, Korea).png',
  'Bonkers (USA, Europe).png',
  'Boogerman - A Pick and Flick Adventure (Europe).png',
  'Boogerman - A Pick and Flick Adventure (USA).png',
  'Boogie Woogie Bowling (Japan).png',
  'Boxing Legends of the Ring (USA).png',
  "Bram Stoker's Dracula (Europe).png",
  "Bram Stoker's Dracula (USA).png",
  "Brett Hull Hockey '95 (USA).png"
];